services:
  tuono:
    container_name: tuono-source-container
    hostname: tuono-source-container
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        RUST_VERSION: 1.83
        BASE_OS: bookworm
    image: tuono-source-image
    ports:
      - "3000:3000" # expose default port used by tuono server
    volumes: # mount the project into a volume but node_modules / .pnpm-store / target / ... directories won't by sync from container to host
      - ..:/tuono
      - /tuono/node_modules
      - /tuono/.pnpm-store
      - /tuono/target
      - /tuono/.turbo
      - /tuono/apps/documentation/node_modules
      - /tuono/apps/documentation/target
    tty: true