services:
  tuono:
    container_name: tuono-source-container
    hostname: tuono-source-container
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        RUST_VERSION: 1.83
        BASE_OS: bookworm
        NODE_VERSION: 22.11.0
    image: tuono-source-image
    ports:
      - "3000:3000" # frontend 
      - "3001:3001" # backend
    volumes: # mount the project into a volume but node_modules / .pnpm-store / target / .turbo directories won't by sync from container to host
      - ..:/app
      - /app/node_modules
      - /app/.pnpm-store
      - /app/target
      - /app/.turbo
    tty: true